# Site settings
title: leverage the digital and welcome real life
name: Joe Buhlig
email: joe@joebuhlig.com
description: > # this means to ignore newlines until "baseurl:"
  leverage the digital and welcome real life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joebuhlig.com" # the base hostname & protocol for your site
twitter_username: joebuhlig
github_username:  joebuhlig
tumblr_username: joebuhlig
instagram_username: joe_buhlig
subreddit:  joebuhlig

# Build settings
markdown: kramdown
timezone: America/Chicago
destination: ~/Codebase/joebuhlig_com_site
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Post settings
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Joe Buhlig"