# Site settings
title: Leverage the digital and welcome real life
email: joe@joebuhlig.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: joebuhlig
github_username:  joebuhlig

# Build settings
markdown: kramdown
timezone: America/Chicago
destination: ~/Codebase/joebuhlig_com_site

# Post settings
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Joe Buhlig"