# Site settings
title: leverage the digital and welcome real life
name: Joe Buhlig
email: joe@joebuhlig.com
description: > # this means to ignore newlines until "baseurl:"
  leverage the digital and welcome real life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joebuhlig.com" # the base hostname & protocol for your site
twitter_username: joebuhlig
github_username:  joebuhlig
tumblr_username: joebuhlig
instagram_username: joe_buhlig
subreddit:  joebuhlig

# Build settings
markdown: kramdown
timezone: America/Chicago
destination: ~/Codebase/joebuhlig_com_site
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Collections
collections:
- episodes

# Post settings
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Joe Buhlig"

# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcastSite: http://www.joebuhlig.com

# The cover image for the podcast, will show in search results in iTunes
podcastCoverImg: http://wwww.YourSite.com/imageSize1400x1400-min.jpg

# The name of your podcast
podcastTitle: My Podcast Title

# About You. For iTunes admin. This information is not displayed on the iTunes Store.
podcastOwner: YourName
podcastEmail: your@email.com

# See https://www.apple.com/itunes/podcasts/specs.html near the bottom for valid categories
category: Education
subCategory: Higher Education

# is it too dangerous for the impressionable kiddos?
podcastIsExplicit: "no"


podcastAuthor: Org, brand or individual
podcastDescription: Verbose description of the podcast.
podcastSubtitle: Short description of the podcast - 255 character max.